#!/bin/bash

read -a oldHashedInput <<< $(IFS=' '; sha512sum <<< ${input[1]})

oldHashed=$(cat $passwordStorage)

if [ "$oldHashed" != "$oldHashedInput" ]; then
	printf "INVALID_OLD_PW\n"
	continue
fi

if [ ${#input[2]} -lt $minPasswordLen ]; then
	printf "INVALID_PW\n"
	continue
fi

read -a newHashedInput <<< $(IFS=' '; sha512sum <<< ${input[2]})

echo $newHashedInput > $passwordStorage
printf "OK\n"
