#!/bin/bash

old=$(requestPassword "\n\nPlease enter your current main password: ")
new=$(requestPassword "\nPlease enter your new main password: ")
newAgain=$(requestPassword "\nPlease enter your new main password again: ")

if [ "$new" != "$newAgain" ]; then
	send "\n\nYour new passwords doesn't match.\nAction canceled.\n"
	pause
	continue
fi

reply=$(queryDaemon change-password "$old" "$new")

case $reply in
INVALID_OLD_PW) send "\n\nCurrent password you've entered is invalid.\nAction canceled.\n" ;;
INVALID_PW)     send "\n\nNew password you've entered is invalid.\nAction canceled.\n" ;;
OK)             send "\n\nYour main password was succesfully changed.\n" ;;
esac

pause